/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksDailySnapshotRouteImport } from './routes/api/public/hooks/daily-snapshot'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailySnapshotRoute =
  ApiPublicHooksDailySnapshotRouteImport.update({
    id: '/api/public/hooks/daily-snapshot',
    path: '/api/public/hooks/daily-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/public/hooks/daily-snapshot': typeof ApiPublicHooksDailySnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/public/hooks/daily-snapshot': typeof ApiPublicHooksDailySnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/public/hooks/daily-snapshot': typeof ApiPublicHooksDailySnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/api/public/hooks/daily-snapshot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/public/hooks/daily-snapshot'
  id: '__root__' | '/' | '/login' | '/api/public/hooks/daily-snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiPublicHooksDailySnapshotRoute: typeof ApiPublicHooksDailySnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-snapshot': {
      id: '/api/public/hooks/daily-snapshot'
      path: '/api/public/hooks/daily-snapshot'
      fullPath: '/api/public/hooks/daily-snapshot'
      preLoaderRoute: typeof ApiPublicHooksDailySnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiPublicHooksDailySnapshotRoute: ApiPublicHooksDailySnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
